inherit_from: rubocop-todo.yml
AllCops:
  Include:
    - '**/Rakefile'
    - Gemfile
    - parser-cli_wrapper.gemspec
    - bin/**
    - lib/**/*.rake
  Exclude:
    - pkg/**
    - repos/**
    - vendor/**
StringLiterals:
  EnforcedStyle: single_quotes
